### ISSUE TITLE
Upcoming features

### ISSUE THREAD

**Issue by shusaura85** [shusaura85/notparadoxlauncher#1]
Currently, the following features are planned to be released in the next version:  
- Show a "Play" button to quickly start the game again if the launcher was left open after exiting the game  
- Add support for the command line arguments the game supports (such as no workshop, no mods, borderless window, force dx9, etc)  
- Allow to turn off Steam Overlay  
- Close the launcher a few seconds after the game is launched  
  
If you have any suggestions, comment on this issue

**Comment by foreachthing** [comment]
My 2¢: Resume last City.
So you click that button and go do <_add some lengthy task here_>.

**Comment by shusaura85** [comment]
> My 2¢: Resume last City.

This is included in the support for command line arguments.  
The plan is that when the "resume last save game" option is active, it will start the game automatically with the last saved game.  
For safety, it will add a 3-5 second delay before starting and show a button to cancel the loading of the last save to allow you to go to the menu (if you want to start a new game). This is needed especially if you use a lot of mods (some of witch won't work or won't allow the "exit to menu" option.

**Comment by shusaura85** [comment]
All planned options have been implemented
