### ISSUE TITLE
Can not type anything at advanced section.

### ISSUE THREAD

**Issue by rogaldh** [shusaura85/notparadoxlauncher#15]
Launcher version: 1.3
OS: macOS 10.15.3

I'm faced with an issue. Literally can not type anything at the advanced section of the launcher, but copy/paste works pretty well.

Btw, does advanced section work? I've tried to set some [launch options](https://steamcommunity.com/sharedfiles/filedetails/?id=466981085&searchtext=options) and they do not work it seems (I've tried `--enable-dev-ui`, `-screen-width <width> -screen-height <height>`, `-screen-fullscreen m` and `-windowed` but no luck).

p.s.: thank you for the work 👍

**Comment by shusaura85** [comment]
I'll have a look at it as soon as I can. About the advanced options not working, it might be an issue in the way it handles the parameters entered there.

**Comment by shusaura85** [comment]
Looks like I'll have to make an application bundle for the launcher. When I wrap the launcher binary in an application bundle, the advanced parameters field works fine.  
Apparently the keyboard focus is stolen by the invisible shell window when launched without the application bundle.

**Comment by shusaura85** [comment]
Fixed in release 1.3.1
