### ISSUE TITLE
Why two files?

### ISSUE THREAD

**Issue by missionfloyd** [shusaura85/notparadoxlauncher#19]
Seems to me that all bootstrapper-v2.exe does is run launcher.exe. In fact, launcher.exe can be renamed to bootstrapper-v2.exe and it still works right.

**Comment by shusaura85** [comment]
When I created Not Paradox Launcher, I did it by monitoring how the game interacts with the official launcher and implemented the code to simulate the official launcher, hence the boostrapper-v2 that simply starts the actual launcher.  
The official bootstrapper does a lot more things (like checking for and downloading launcher updates). I simply added the launcher execution part. It was easier to make it as 2 binaries that look and work in a similar matter to the official launcher, as I couldn't know if the game checks if a specific binary name is active.
