### ISSUE TITLE
Settings are ignored

### ISSUE THREAD

**Issue by romanov** [shusaura85/notparadoxlauncher#20]
```
{
	"continuelastsave": false,
	"noworkshop": false,
	"disablemods": false,
	"nolog": false,
	"windowmode": "borderless",
	"forced3d9": false,
	"forceopengl": false,
	"advanced": "-screen-width 3840 -screen-height 1600"
}
```

The game runs in fullscreen instead of borderless with standard HD resolution.

**Comment by shusaura85** [comment]
Thanks for the report, I'll look into it and see what's the problem with the settings

**Comment by shusaura85** [comment]
The problem appears to be with the game and not the launcher.  
All parameters are properly sent to the game. I tested this with a separate program that receives the start command from the launcher and shows the received parameters.  
  
Borderless mode (-popupwindow) doesn't work with the screen-width and screen-height params, as borderless mode creates a window that is the size of the main screen resolution, while the screen-width and screen-height params specify the resolution for the full screen mode.

**Comment by romanov** [comment]
Ok, but settings are ignored even in fullscreen.

**Comment by shusaura85** [comment]
There is nothing I can do to make the game respect the options you give it. The launcher can only pass them to the game, it's completely up to the game if it accepts them :(  
  
It ignored the screen-width and screen-height options for me as well. I tried with window mode, the specified resolution was used only for the first few seconds before the game started rendering it's startup logos, after that, it resized the window to the screen resolution (with the bottom part of the window outside the screen height)

**Comment by romanov** [comment]
Thank you for information.
