### ISSUE TITLE
Small error in readme

### ISSUE THREAD

**Issue by Imsvale** [shusaura85/notparadoxlauncher#7]
The readme says: 3. Delete the file "launcherpath" from "%APPDATA%\Local\Paradox Interactive\"

%APPDATA% points to AppData\Roaming, whereas %LOCALAPPDATA% points to AppData\Local\.

Correct would be: 3. Delete the file "launcherpath" from "%LOCALAPPDATA%\Paradox Interactive\"

**Comment by shusaura85** [comment]
Thanks. I've fixed it for the next version.
