### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by naylin-mi** [shusaura85/notparadoxlauncher#9]
This is great! I don't know why Paradox decided that they needed a launcher in the first place. Make an already long to load game even longer loading! Problem solved.

Anyway, I've got a request. How about a dedicated button (like the resume last save button) that launches the game in --noWorkshop mode? I know that I can change it from the options menu. However, being an asset/map creator, I frequently open the game in --noWorkshop in order to work on/build an asset, exit the game, re-open to last saved game (with the workshop enabled) to test the asset, exit, repeat... A dedicated --noWorkshop button could be very handy!

Thanks for your consideration,
~Naylin

**Comment by shusaura85** [comment]
Good ideea. I'll add the option sometime this weekend or when I have some time available

**Comment by shusaura85** [comment]
Version 1.2.0 is out with the dedicated button to enable / disable Steam Workshop

**Comment by naylin-mi** [comment]
Cool, I'll check it out when I get home!
